### PR TITLE
Fixed Navbar inconsistency and responsiveness of code snippets

### PR DESCRIPTION
**Pull request by Miran-Firdausi**
Now code snippets shows two column on larger devices and one column in mobile devices

### CODE REVIEW

**Comment by Miran-Firdausi** [comment]
Mark this under hacktoberfest-accepted

**Comment by Miran-Firdausi** [comment]
Made compulsory to enter username and password to enter before clicking on sign up to prevent error.

**Comment by Sriram-Ramakrishnan** [comment]
Great work with the responsiveness and making the signup and login fields compulsory. However, while aligning the code, the indentation for the below code snippets have been removed as shown below. 
image

Add indentation to all 10 code snippets and commit it to this pull request. You can refer the website for the indentation which needs to be added.

**Comment by Miran-Firdausi** [comment]
Yeah, did not noticed that. Will do the changes.

**Pull request merged**
